mod icon_brand;
mod icon_close;
mod icon_dashboard;
mod icon_file;
mod icon_maximize;
mod icon_menu_close;
mod icon_menu_open;
mod icon_minimize;
mod icon_moon;
mod icon_shield;
mod icon_sun;

pub use icon_brand::*;
pub use icon_close::*;
pub use icon_dashboard::*;
pub use icon_file::*;
pub use icon_maximize::*;
pub use icon_menu_close::*;
pub use icon_menu_open::*;
pub use icon_minimize::*;
pub use icon_moon::*;
pub use icon_shield::*;
pub use icon_sun::*;
